### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by 20after4** [joakin/group-phabricator-notifications#1]
I'd like to port this extension to Firefox (essentially this is as straightforward as simply uploading it to the mozilla addons portal) but I don't see a license anywhere in this repository. Do you mind choosing a license for this extension that would allow distribution of the source?

**Comment by joakin** [comment]
Woops, I thought I had MIT in a package.json but it seems like I didn't add it.

I'll add it when I get a moment, happy to accept a PR too if you want 👍
